////////////////////////////////////////////////////////////////////////////////
// Formal Verification Testbench for FIFO
// Generated by Multi-Stage Assertion Generator - Stage 3
//
// This testbench includes:
// - All module parameters
// - All ports declared as logic
// - DUT instantiation (FIFO as DUT)
// - Refined assertions with correct signal references
// - Internal signals accessed via DUT.signal_name
// - Default clocking and reset handling
//
// Note: Incremental progress saved to: output/refined_assertions_progress.sv
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
// Testbench for FIFO
// Auto-generated by assertion generation pipeline
// Contains DUT instantiation and formal verification assertions
////////////////////////////////////////////////////////////////////////////////

module FIFO_tb;

    // Parameters
    parameter WIDTH = 8;
    parameter DEPTH = 16;
    parameter FIFO_DEPTH = 16;

    // Port declarations (as logic)
    logic data_in;
    logic wr_en;
    logic rd_en;
    logic clk;
    logic rst_n;
    logic full;
    logic empty;
    logic almostfull;
    logic almostempty;
    logic wr_ack;
    logic overflow;
    logic underflow;
    logic data_out;

    // DUT Instantiation
    FIFO #(
        .WIDTH(WIDTH),
        .DEPTH(DEPTH),
        .FIFO_DEPTH(FIFO_DEPTH)
    ) DUT (
        .data_in(data_in),
        .wr_en(wr_en),
        .rd_en(rd_en),
        .clk(clk),
        .rst_n(rst_n),
        .full(full),
        .empty(empty),
        .almostfull(almostfull),
        .almostempty(almostempty),
        .wr_ack(wr_ack),
        .overflow(overflow),
        .underflow(underflow),
        .data_out(data_out)
    );

    // Default clocking and reset handling
    default clocking cb @(posedge clk);
    endclocking

    default disable iff (!rst_n);

    // Formal Verification Assertions
    assert property (@(posedge clk) $rose(rst_n) |=> empty);

    assert property (@(posedge clk) (full && wr_en) |-> overflow);

    as__fifo_underflow: assert property (@(posedge clk) disable iff (!rst_n) (rd_en && empty) |-> underflow);

    as__wr_ack_next_cycle: assert property (@(posedge clk) disable iff (!rst_n) (wr_en && !full) |=> wr_ack);

    as__write_succeeds_on_simultaneous_read_write_empty: assert property (@(posedge clk) disable iff (!rst_n) (rd_en && wr_en && empty) |=> wr_ack);

endmodule

////////////////////////////////////////////////////////////////////////////////
// End of Formal Verification Testbench
////////////////////////////////////////////////////////////////////////////////
