////////////////////////////////////////////////////////////////////////////////
// Formal Verification Testbench for rr_arbiter
// Generated by Multi-Stage Assertion Generator - Stage 3
//
// This testbench includes:
// - All module parameters
// - All ports declared as logic
// - DUT instantiation (rr_arbiter as DUT)
// - Refined assertions with correct signal references
// - Internal signals accessed via DUT.signal_name
// - Default clocking and reset handling
//
// Note: Incremental progress saved to: output/refined_assertions_progress.sv
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
// Testbench for rr_arbiter
// Auto-generated by assertion generation pipeline
// Contains DUT instantiation and formal verification assertions
////////////////////////////////////////////////////////////////////////////////

module rr_arbiter_tb;

    // Parameters
    parameter CLIENTS = 4
)(
    input  logic                 clk,
    input  logic                 rst_n,
    input  logic [CLIENTS-1:0]   req,
    output logic [CLIENTS-1:0]   gnt
);

    // Port declarations (as logic)
    logic clk;
    logic rst_n;
    logic [CLIENTS-1:0] req;
    logic [CLIENTS-1:0] gnt;

    // DUT Instantiation
    rr_arbiter #(
        .CLIENTS(CLIENTS)
    ) DUT (
        .clk(clk),
        .rst_n(rst_n),
        .req(req),
        .gnt(gnt)
    );

    // Default clocking and reset handling
    default clocking cb @(posedge clk);
    endclocking

    default disable iff (!rst_n);

    // Formal Verification Assertions
    assert property (@(posedge clk) $onehot0(req) |-> 1);

    generate
        for (genvar i = 0; i < WIDTH; i++) begin
        gnt_req_match: assert property (@(posedge clk) disable iff (!rst_n) gnt[i] |-> req[i] );
    end
    endgenerate

    as__clk_rst_n_req_gnt_same_cycle: assert property (|clk |-> |rst_n |-> |req |=> |gnt);

    generate
        for (genvar i = 0; i < NUM_REQS; i++) begin
        as__round_robin_arb_fairness: assert property (gnt[i] && req[i] |=> gnt[i] && req[i] |-> !gnt[i] throughout ($countones(req & ~(1'b1<<i)) > 0) );
    end
    endgenerate

    assert property (@(posedge clk) disable iff (!rst_n) !rst_n |-> gnt == '0);

    assert property ($changed(req) |-> gnt);

endmodule

////////////////////////////////////////////////////////////////////////////////
// End of Formal Verification Testbench
////////////////////////////////////////////////////////////////////////////////
